version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:17.4
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tz-effective-mobile

volumes:
  postgres_data:


networks:
  tz-effective-mobile:
